accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('', views.home, name='home'), 
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),  
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('review/<int:pk>/', views.add_review, name='review'),
]   

examen/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CourseRequest(models.Model):
    COURSE=[
        ("web_design", "Основы веб-дизайна"),
        ("database_design", "Основы проектирования баз данных"),
        ("algorithms_programming", "Основы алгоритмизации и программирования"),
    ]
    
    STATUS=[
        ("not_started","Ещё не начал"),
        ("in_progress","Начал"),
         ("finished","Завершил"),
    ]

    user=models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.CharField(max_length=50,choices=COURSE)
    date_start = models.DateField()
    status = models.CharField(max_length=20,choices=STATUS,default="not_started")
    created_at=models.DateTimeField(auto_now_add=True)

    review = models.TextField(blank=True, null=True, verbose_name="Отзыв")

    def __str__(self):
        return f"{self.user.username} - {self.course}"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
import re
from datetime import date
from django.contrib.auth import authenticate
from .models import CourseRequest

class RegisterForm(forms.ModelForm):
    full_name = forms.CharField(label='ФИО',max_length=100,required=True,widget=forms.TextInput(attrs={'placeholder':'Иванов Иван Иванович'}))
    username = forms.CharField(label='Логин',min_length=6,max_length=30,required=True,widget=forms.TextInput(attrs={'placeholder':'login123'}))
    password1 = forms.CharField(label='пароль',min_length=8,widget=forms.PasswordInput,required=True)
    password2 = forms.CharField(label='повторите пароль', widget=forms.PasswordInput, required=True)
    email=forms.EmailField(label='почта',required=True,widget=forms.EmailInput(attrs={'placeholder':'example@mail.com'}))
    phone = forms.CharField(label='телефон',required=True,widget=forms.TextInput(attrs={'placeholder':'8(999)123-45-67'}))
    
    class Meta:
        model=User
        fields = ('username', 'full_name', 'email', 'phone', 'password1', 'password2')

    def clean_password2(self):
        p1 = self.cleaned_data.get('password1')
        p2 = self.cleaned_data.get('password2')

        if p1 != p2:
            raise forms.ValidationError("Пароли не совпадают!")

        validate_password(p1)
        return p2
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not re.fullmatch(r'[A-Za-z0-9]{6,}',username):
            raise ValidationError ('Логин должен содержать только латиницу и цифры, минимум 6 символов')
        if User.objects.filter(username=username).exists():
            raise ValidationError("Такой логин уже существует")
        return username
    
    def clean_full_name(self):
        full_name = self.cleaned_data.get('full_name')
        if not re.fullmatch(r'[А-Яа-яЁё]+ [А-Яа-яЁё]+ [А-Яа-яЁё]+', full_name):
            raise ValidationError("ФИО только кириллица и пробелы")
        return full_name
    
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if len(phone) != 15:
            raise forms.ValidationError("Некорректный номер")
        return phone
    
class CourseRequestForm(forms.ModelForm):
    date_start = forms.DateField(
        label='Дата начала',
        widget=forms.DateInput(
            attrs={
                'type': 'date', 
                'class': 'input-field'
            }
        )
    )

    class Meta:
        model = CourseRequest
        fields = ['course', 'date_start']
        labels = {
            'course': 'Курс',
        }
        widgets = {
            'course': forms.Select(attrs={'class': 'input-field'}),
        }

    def clean_date_start(self):
        from datetime import date
        selected_date = self.cleaned_data.get("date_start")

        if selected_date < date.today():
            raise forms.ValidationError("Нельзя выбрать дату в прошлом!")

        return selected_date


class LoginForm(forms.Form):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'placeholder': 'login123'}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        if not username or not password:
            raise forms.ValidationError("Все поля должны быть заполнены!")

 
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError("Неверное имя пользователя или пароль")

        cleaned_data['user'] = user
        return cleaned_data
        
 
class ReviewForm(forms.ModelForm):
    class Meta:
        model = CourseRequest
        fields = ['review']
        widgets = {
            'review': forms.Textarea(
                attrs={
                    'class': 'input-field review-textarea',
                    'placeholder': 'Оставьте ваш отзыв здесь...',
                    'rows': 6
                }
            )
        }
    

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm,CourseRequestForm, ReviewForm,LoginForm
from .models import CourseRequest
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

from django.contrib.auth.models import User


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1'],
                first_name=form.cleaned_data['full_name'], 
            )
            
            messages.success(request, f"Добро пожаловать, {user.username}!")
            return redirect('login')  
        else:
            messages.error(request, "Проверьте корректность введённых данных")
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

@login_required
def home(request):
    if request.method == 'POST':
        form = CourseRequestForm(request.POST)
        if form.is_valid():
            course_request = form.save(commit=False)
            course_request.user = request.user
            course_request.save()
            messages.success(request, 'Заявка успешно отправлена!')
            return redirect('home')
    else:
        form = CourseRequestForm()
    return render(request, 'accounts/home.html', {'form': form})

@login_required
def profile(request):
    requests = CourseRequest.objects.filter(user=request.user)
    return render (request,"accounts/profile.html",{"requests":requests})

class LoginView(LoginView):
    template_name = 'accounts/login.html'

    def get_success_url(self):
        if self.request.user.is_superuser:
            return '/admin/'
        return reverse_lazy('home') 
    
@login_required
def add_review(request, pk):
    course_request = get_object_or_404(CourseRequest, pk=pk, user=request.user)
    
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=course_request)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ReviewForm(instance=course_request)
    
    return render(request, 'accounts/review.html', {'form': form})

def login_view(request):
    form = LoginForm(request.POST or None)
    
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)

               
                if user.is_superuser:
                    return redirect('/admin/')
                
               
                return redirect('home')
            else:
                form.add_error(None, "Неправильный логин или пароль")
    
    return render(request, 'accounts/login.html', {'form': form})

templates/accounts/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="slider-container">
    <div class="slider">
        <div class="slide active">
            <img src="{% static 'images/img1.jpg' %}" alt="">
        </div>
        <div class="slide">
            <img src="{% static 'images/img2.jpg' %}" alt="">
        </div>
        <div class="slide">
            <img src="{% static 'images/img3.jpg' %}" alt="">
        </div>
    </div>

    <button class="prev-btn">❮</button>
    <button class="next-btn">❯</button>
</div>

<div class="home-container">
    <h1>Добро пожаловать, {{ user.username }}!</h1>

    <div class="form-card">
        <h2>Оставить заявку на курс</h2>

        <form method="post">
            {% csrf_token %}
{% for field in form %}
    <div class="field">
        {{ field.label_tag }}
        {{ field }}
        {% for error in field.errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}


            <button type="submit" class="send-btn">Отправить</button>
        </form>
    </div>
</div>
<script src="{% static 'js/slider.js' %}"></script>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1 >Вход</h1>

<form method="post" class="form-card">
    {% csrf_token %}

    {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {{ field }}

           
      
        </div>
    {% endfor %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="error" >
                {{ error }}
            </p>
        {% endfor %}
    {% endif %}

    <button type="submit">Войти</button>
</form>

<p style="text-align:center;">Нет аккаунта? <a href="{% url 'register' %}">Регистрация</a></p>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}

<h1>Ваши заявки</h1>

<div class="profile-card">

{% if requests %}
    <table class="requests-table">
        <tr>
            <th>Курс</th>
            <th>Дата начала</th>
            <th>Статус</th>
            <th>Отзыв</th>
        </tr>

        {% for r in requests %}
        <tr>
            <td>{{ r.get_course_display }}</td>
            <td>{{ r.date_start|date:"d.m.Y" }}</td>
            <td>{{ r.get_status_display }}</td>
            <td>
                {% if r.status == 'finished' %}
                    {% if r.review %}
                        Отзыв оставлен
                    {% else %}
                        <a href="{% url 'review' r.pk %}" class="send-btn">Оставить отзыв</a>
                    {% endif %}
                {% else %}
                    -
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>У вас пока нет заявок.</p>
{% endif %}

</div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Регистрация</h1>

<form method="post" class="form-card">
    {% csrf_token %}

    {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {{ field }}

            {% for error in field.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}

    <button type="submit">Зарегистрироваться</button>
</form>

<p>Уже есть аккаунт? <a href="{% url 'login' %}">Войти</a></p>

<script src="{% static 'js/phonemask.js' %}"></script>
{% endblock %}

templates/accounts/review.html
{% extends "base.html" %}

{% block content %}
<div class="home-container">
    <div class="form-card review-card">
        <h2 class="form-title">Оставить отзыв</h2>

        <form method="post" class="review-form">
            {% csrf_token %}
            <div class="field">
                {{ form.review.label_tag }}
     {{ form.review }}
                {% for error in form.review.errors %}
                    <p class="error">{{ error }}</p>
                {% endfor %}
            </div>

            <button type="submit" class="review-btn">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}